services:
  - type: web
    name: edu-platform
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: ADMIN_USERNAME
        value: redaawad
      - key: ADMIN_PASSWORD
        sync: false
      - key: SUPABASE_PROJECT_ID
        value: feezcqadsabyxoyxhcwy
      - key: SUPABASE_PUBLISHABLE_KEY
        sync: false
      - key: SUPABASE_SECRET_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
    disk:
      name: edu-data
      mountPath: /var/data
      sizeGB: 10
